version: '3.7'
services:
  nginx:
    build: .
    image: nginx:stable
    container_name: nginx
    environment:
      - TZ=Asia/Seoul
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
  # deploy:
    # resources:
      # limits:
        # cpus: '0.5'
        # memory: 1024M
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nue-fans/fans:/usr/share/nginx/html:ro
